name: win-docker

on:
  workflow_dispatch:


jobs:
  win-setup:
    runs-on: windows-2019
    
    steps:
      - uses: actions/checkout@v3
      
      #- name: Check Hyper-V and Docker
      #  run: |
      #    Get-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V
      #    docker version
      #    docker images

      - name: Compose win-sshd docker containter
        run: |
          # compose docker container
          cd ci/ssh-win
          docker compose up -d --build
          
          # retrieve id_rsa file for public key authentication
          mkdir $env:USERPROFILE/.ssh/
          docker run ipyparallel-sshd powershell.exe -Command "type C:\Users\ciuser\.ssh\id_rsa" | out-file -encoding ascii $env:USERPROFILE/.ssh/id_rsa

      - name: ssh connection and copy files
        run: |
          # make first ssh connection to docker container (requires StrictHostKeyChecking set to no ) and create dir
          # verbose: remove -v parameter for less output messages
          ssh -o "StrictHostKeyChecking no" ciuser@localhost -p 2222 -v mkdir c:\src\ipyparallel
          
          # zip ipyparallel files 
          $exclude = @("__pycache__","node_modules")
          $files = Get-ChildItem -Path "ipyparallel" -Exclude $exclude
          Compress-Archive -Path $files -DestinationPath ipyparallel.zip -CompressionLevel Fastest

          # copy file into docker (we need to do it over ssh since docker copy or mount doesn't work in Hyper-V)
          scp -P 2222 ipyparallel.zip ciuser@localhost:c:\src\ipyparallel
          
          # deflate ipyparallel files
          ssh ciuser@localhost -p 2222 powershell.exe Expand-Archive -Path c:\src\ipyparallel\ipyparallel.zip -DestinationPath c:\src\ipyparallel

          # pip install ipyparallel files
          ssh ciuser@localhost -p 2222 "cd c:\src\ipyparallel && pip install -e ."

      - name: test ipyparallel
        run: |
          # check environment
          ssh ciuser@localhost -p 2222 pip freeze
          
          # send test command
          ssh ciuser@localhost -p 2222 ipcluster
